# constants related to paths of various parts of project
path:
  data:
    raw: 'data/raw/'
    featured: 'data/featured/'
    training: 'data/training'
    validation: 'data/validation'
    testing: 'data/testing'

# constants related to pipeline package handling data
pipeline:

  # constants related to downloading the data
  exchange: 'binance'
  symbols:
    - 'BNB/USDT'
    - 'BTC/USDT'
    - 'ETH/USDT'
    - 'SOL/USDT'

  timeframe: '1h'

  start_date: '2020-06-01'
  end_date: '2025-12-31'

  training_start_date: '2021-01-01'
  training_end_date: '2024-12-31'
  validation_start_date: '2025-01-01'
  validation_end_date: '2025-06-30'
  testing_start_date: '2025-07-01'
  testing_end_date: '2025-12-31'

  # constants related to feature engineering
  timeperiod_cat: 3
  timeperiod_cat0: 9
  timeperiod_cat1: 12
  timeperiod_cat2: 14
  timeperiod_cat3: 26
  timeperiod_cat4: 50
