[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Alpha9"
version = "1.0.0"
authors = [
    { name="Divyansh Gupta", email="thedivyanshgupta.100@gmail.com" },
    { name="Sarath Chandra Jandhyala", email="user@example.com" },
    { name="Aayush Sharma", email="user@example.com" }
]
description = "An autonomous multi-asset trading agent for crypto"
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]

dependencies = [
    "ccxt",
    "ta-lib",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "statsmodels",
    "python-dotenv",
    "pyyaml",
    "torch",
    "torchvision",
    "torchaudio"
]

[project.urls]
"Github" = "https://github.com/DivyanshGupta2006/Project-Alpha9"

[project.scripts]
Alpha9 = "Alpha9.main:start"